[tool.poetry]
name = "spoofbot"
version = "1.1.1"
description = "A python requests wrapper that forms requests like real browsers and offers caching"
authors = ["raember <raember@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://pypi.org/project/spoofbot/"
repository = "https://github.com/raember/spoofbot"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = "^3.9"
urllib3 = "^1.26.6"
requests = "^2.26.0"
bs4 = "^0.0.1"
Pillow = "^8.3.1"
toposort = "^1.6"
Brotli = "^1.0.9"
publicsuffix2 = "^2.20191221"
loguru = "^0.5.3"
mitmproxy = "^7.0.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
